/* Live listing-level inventory management with API-backed editing. */
const adminApiReady = window.mlmApi ? Promise.resolve() : new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = '../../js/api.js'; script.onload = resolve; script.onerror = reject; document.head.appendChild(script); });
adminApiReady.then(() => window.mlmSessionReady).then(() => mlmSession.requireAdmin()).then(async () => {
  const rows = document.querySelector('#equipmentRows'); if (!rows) return;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const classify = name => { const n = String(name || '').toLowerCase(); if (/camera|a6400|zv-e10|rx100/.test(n)) return 'Cameras'; if (/lens|mm f|art/.test(n)) return 'Lenses'; if (/mic|rode|røde|sennheiser|hollyland|zoom|headphone|mixer|recorder|audio/.test(n)) return 'Audio'; if (/light|godox|aputure|colbor|softbox|stand/.test(n)) return 'Lighting'; return 'Accessories'; };
  const brand = name => { const n = String(name || '').toLowerCase(); if (n.includes('sony')) return 'Sony'; if (n.includes('canon')) return 'Canon'; if (n.includes('sigma')) return 'Sigma'; if (n.includes('ttartisan')) return 'TTArtisans'; if (n.includes('godox')) return 'Godox'; if (n.includes('rode') || n.includes('røde')) return 'RØDE'; if (n.includes('hollyland')) return 'Hollyland'; if (n.includes('zoom')) return 'Zoom'; return ''; };
  const groupUnits = units => [...units.reduce((groups, unit) => { const key = unit.listing_id || unit.name; const group = groups.get(key) || { ...unit, units: [] }; group.units.push(unit); groups.set(key, group); return groups; }, new Map()).values()].map(group => { const available = group.units.filter(unit => unit.status === 'available'); return { ...group, id: (available[0] || group.units[0])?.id, total_quantity: group.units.length, available_quantity: available.length, checked_out_quantity: group.units.filter(unit => ['picked_up', 'overdue'].includes(unit.status)).length, units: undefined }; });
  let equipment = [];
  const renderBrands = () => { const select = document.querySelector('#adminBrandFilter'); if (!select) return; const current = select.value; const values = [...new Set(equipment.map(item => brand(item.name)).filter(Boolean))].sort(); select.innerHTML = '<option value="">All brands</option>' + values.map(value => `<option value="${esc(value)}">${esc(value)}</option>`).join(''); if (values.includes(current)) select.value = current; };
  const render = category => { const query = (document.querySelector('#equipmentSearch')?.value || '').toLowerCase(); const selectedBrand = document.querySelector('#adminBrandFilter')?.value || ''; const filtered = equipment.filter(item => (category === 'All' || classify(item.name).toLowerCase() === category.toLowerCase()) && (!selectedBrand || brand(item.name) === selectedBrand) && [item.name, item.asset_code, item.serial_number, item.description, item.location].join(' ').toLowerCase().includes(query)); rows.innerHTML = filtered.map(item => `<tr><td><b>${esc(item.name)}</b><br><small>${esc(item.description || '')}</small></td><td>${esc(item.category || classify(item.name))}</td><td>${esc(item.total_quantity ?? 0)}</td><td>${esc(item.available_quantity ?? 0)}</td><td>${esc(item.checked_out_quantity ?? 0)}</td><td><span class="status ${esc(item.status || 'unknown')}">${esc(item.status || 'unknown')}</span></td><td><button class="btn btn-ghost btn-sm" data-equipment-edit="${item.id}">Edit</button></td></tr>`).join('') || '<tr><td colspan="7" class="empty">No equipment matches this filter.</td></tr>'; document.querySelectorAll('[data-equipment-edit]').forEach(button => button.onclick = () => openEditor(equipment.find(item => String(item.id) === String(button.dataset.equipmentEdit)))); };
  const closeEditor = () => document.querySelector('#equipmentEditor')?.remove();
  const openEditor = item => { if (!item) return; closeEditor(); const dialog = document.createElement('div'); dialog.id = 'equipmentEditor'; dialog.className = 'modal-backdrop'; dialog.innerHTML = `<section class="equipment-editor" role="dialog" aria-modal="true" aria-labelledby="equipmentEditorTitle"><div class="editor-head"><div><h2 id="equipmentEditorTitle">Edit equipment</h2><p>Changes are saved to the Media Lab inventory.</p></div><button type="button" class="outline" data-editor-close aria-label="Close editor">×</button></div><form class="editor-form"><label>Name<input name="name" required value="${esc(item.name)}"></label><label>Asset code<input name="assetCode" required value="${esc(item.asset_code)}"></label><label>Serial number<input name="serialNumber" value="${esc(item.serial_number)}"></label><label>Status<select name="status"><option>available</option><option>requested</option><option>pickup_pending</option><option>picked_up</option><option>overdue</option><option>damaged</option><option>maintenance</option><option>retired</option><option>lost</option></select></label><label>Location<input name="location" value="${esc(item.location)}"></label><label class="editor-full">Description<textarea name="description">${esc(item.description)}</textarea></label><div class="editor-actions"><button type="button" class="outline" data-editor-close>Cancel</button><button class="primary" type="submit">Save changes</button></div></form></section>`; document.body.appendChild(dialog); dialog.querySelector('[name="status"]').value = item.status || 'available'; dialog.querySelectorAll('[data-editor-close]').forEach(button => button.onclick = closeEditor); dialog.onclick = event => { if (event.target === dialog) closeEditor(); }; dialog.querySelector('form').onsubmit = async event => { event.preventDefault(); const payload = Object.fromEntries(new FormData(event.currentTarget).entries()); try { await mlmApi.updateEquipment(item.id, payload); const refreshed = await mlmApi.equipment({ limit: 1000 }); const units = Array.isArray(refreshed) ? refreshed : (refreshed.equipment || refreshed.items || []); equipment = groupUnits(units); renderBrands(); closeEditor(); render(document.querySelector('.admin-tabs .selected')?.dataset.filter || 'All'); } catch (error) { mlmUiError(error.message); } }; dialog.querySelector('[name="name"]').focus(); };
  try { const [equipmentResult, listingResult] = await Promise.all([mlmApi.equipment({ limit: 1000 }), mlmApi.listings()]); const units = Array.isArray(equipmentResult) ? equipmentResult : (equipmentResult.equipment || equipmentResult.items || []); const listings = Array.isArray(listingResult) ? listingResult : (listingResult.listings || listingResult.items || []); const unitMap = new Map(units.map(unit => [Number(unit.id), unit])); equipment = listings.map(listing => { const representative = unitMap.get(Number(listing.available_equipment_ids?.[0] || listing.equipment_ids?.[0] || listing.id)) || {}; return { ...representative, ...listing, id: representative.id || listing.id, total_quantity: Number(listing.total_quantity ?? listing.quantity ?? 0), available_quantity: Number(listing.available_quantity ?? 0), checked_out_quantity: Number(listing.checked_out_quantity ?? 0) }; }); renderBrands(); render('All'); document.querySelector('#equipmentSearch')?.addEventListener('input', () => render(document.querySelector('.admin-tabs .selected')?.dataset.filter || 'All')); document.querySelector('#adminBrandFilter')?.addEventListener('change', () => render(document.querySelector('.admin-tabs .selected')?.dataset.filter || 'All')); document.querySelectorAll('.admin-tabs button').forEach(button => button.onclick = () => { document.querySelectorAll('.admin-tabs button').forEach(x => x.classList.remove('selected')); button.classList.add('selected'); render(button.dataset.filter || button.textContent.trim()); }); } catch (error) { rows.innerHTML = `<tr><td colspan="7">${esc(error.message)}</td></tr>`; }
});
