(async function () {
  if (!window.mlmApi) await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = '../../js/api.js'; script.onload = resolve; script.onerror = reject; document.head.appendChild(script); });
  await window.mlmSessionReady; await mlmSession.requireStaff();
  const target = document.querySelector('#reportRows'); if (!target) return;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const format = value => value ? new Date(value).toLocaleString() : '—';
  let reports = [];
  const openReport = report => { if (!report) return; const existing = document.querySelector('#damageReportModal'); if (existing) existing.remove(); const modal = document.createElement('div'); modal.id = 'damageReportModal'; modal.className = 'modal-backdrop'; modal.innerHTML = `<section class="damage-report-modal" role="dialog" aria-modal="true" aria-labelledby="damageReportTitle"><div class="editor-head"><div><h2 id="damageReportTitle">Damage report #${report.id}</h2><p>${esc(format(report.created_at))}</p></div><button type="button" class="outline" data-report-close aria-label="Close report">×</button></div><div class="damage-report-grid"><article><b>Equipment</b><p>${esc(report.equipment_name)}</p><small>Asset: ${esc(report.asset_code || '—')} · Serial: ${esc(report.serial_number || '—')}</small></article><article><b>Current status</b><p><span class="status damaged">${esc(report.equipment_status || 'unknown')}</span></p><small>Location: ${esc(report.location || '—')}</small></article><article><b>Borrower</b><p>${esc(report.requester_name)}</p><small>${esc(report.requester_email || '')} · Request #${esc(report.request_id)}</small></article><article><b>Report status</b><p>${report.resolved ? 'Resolved' : 'Open'}</p><small>Severity: ${esc(report.severity || 'unknown')}</small></article><article class="damage-report-full"><b>Description</b><p>${esc(report.description)}</p></article><article class="damage-report-full"><b>Return information</b><p>Condition: ${esc(report.return_condition || '—')}</p><p>Notes: ${esc(report.return_notes || '—')}</p></article></div><div class="editor-actions"><button type="button" class="primary" data-report-close>Close</button></div></section>`; document.body.appendChild(modal); modal.querySelectorAll('[data-report-close]').forEach(button => button.onclick = () => modal.remove()); modal.onclick = event => { if (event.target === modal) modal.remove(); }; };
  const renderSeverityOptions = () => { const select = document.querySelector('#reportSeverity'); if (!select) return; const current = select.value; const values = [...new Set(reports.map(report => String(report.severity || '').trim()).filter(Boolean))].sort(); select.innerHTML = '<option value="">All severities</option>' + values.map(value => `<option value="${esc(value)}">${esc(value)}</option>`).join(''); if (values.includes(current)) select.value = current; };
  const render = () => { renderSeverityOptions(); const query = (document.querySelector('#reportSearch')?.value || '').toLowerCase(); const status = document.querySelector('#reportStatus')?.value || 'open'; const severity = document.querySelector('#reportSeverity')?.value || ''; const visible = reports.filter(report => (!query || [report.id, report.equipment_name, report.asset_code, report.requester_name, report.description].join(' ').toLowerCase().includes(query)) && (status === 'all' || (status === 'open' ? !report.resolved : Boolean(report.resolved))) && (!severity || report.severity === severity)); target.innerHTML = visible.map(report => `<tr><td><b>#${report.id}</b><br><small>${esc(format(report.created_at))}</small></td><td><b>${esc(report.equipment_name)}</b><br><small>${esc(report.asset_code || report.serial_number || '')}</small></td><td>${esc(report.requester_name)}<br><small>Request #${esc(report.request_id)}</small></td><td><span class="status ${report.equipment_status === 'damaged' ? 'damaged' : 'pending'}">${esc(report.equipment_status || 'unknown')}</span></td><td>${esc(report.severity || 'unknown')}</td><td>${esc(report.description)}</td><td><button class="btn btn-ghost btn-sm" data-report-id="${esc(report.id)}">View report</button></td></tr>`).join('') || '<tr><td colspan="7" class="empty">No damage reports match these filters.</td></tr>'; document.querySelectorAll('[data-report-id]').forEach(button => button.onclick = () => openReport(reports.find(report => String(report.id) === String(button.dataset.reportId)))); };
  const parse = value => { if (!value) return null; try { return JSON.parse(value); } catch { return value; } };
  const pendingSubmissionReports = requests => requests.flatMap(request => {
    const submission = request.return_submission; if (!submission) return [];
    const raw = parse(submission.damage_description || submission.damageDescription); if (!raw) return [];
    const entries = Array.isArray(raw) ? raw : [{ notes: String(raw), severity: 'reported' }];
    return entries.filter(entry => entry && (entry.notes || entry.description || entry.severity)).map((entry, index) => {
      const item = (request.items || []).find(candidate => Number(candidate.id) === Number(entry.requestItemId));
      return { id: `submission-${request.id}-${entry.requestItemId || index}`, request_item_id: entry.requestItemId || item?.id, request_id: request.id, equipment_name: entry.equipment || item?.name || item?.equipment_id || 'Equipment', asset_code: item?.asset_code, equipment_status: item?.equipment_status || 'return_submitted', requester_name: request.requester_name, requester_email: request.requester_email, severity: entry.severity || 'reported', description: entry.notes || entry.description || 'Damage noted in student return submission', resolved: false, created_at: submission.submitted_at || submission.claimed_returned_at, return_condition: entry.condition || submission.student_condition, return_notes: entry.notes || submission.damage_description, source: 'student_return_submission' };
    });
  });
  const load = async () => { try { const query = new URLSearchParams({ q: document.querySelector('#reportSearch')?.value || '' }); const damageResult = await mlmApi.damageReports(`?${query}`); reports = Array.isArray(damageResult) ? damageResult : (damageResult.reports || []); render(); } catch (error) { target.innerHTML = `<tr><td colspan="7">${esc(error.message)}</td></tr>`; } };
  document.querySelector('#reportSearch')?.addEventListener('input', render); document.querySelector('#reportStatus')?.addEventListener('change', render); document.querySelector('#reportSeverity')?.addEventListener('change', render); await load();
})();
