const bookingsApiReady = window.mlmApi ? Promise.resolve() : new Promise(resolve => { const s = document.createElement('script'); s.src = '../js/api.js'; s.onload = resolve; document.head.appendChild(s); });
bookingsApiReady.then(() => window.mlmSessionReady).then(() => mlmSession.requireAuth()).then(() => {
  const $ = selector => document.querySelector(selector); let cart = JSON.parse(localStorage.getItem('mlmCart') || '[]');
  const toast = message => { $('#toast').textContent = message; $('#toast').classList.add('show'); setTimeout(() => $('#toast').classList.remove('show'), 3000); };
  const draw = () => { $('#itemCount').textContent = `(${cart.length} Item${cart.length === 1 ? '' : 's'} Selected)`; $('#cartItems').innerHTML = cart.length ? cart.map(x => `<article class="cart-item"><div class="cart-thumb">▧</div><div><span class="tag">${x.status || 'Equipment'}</span><h3>${x.name}</h3><p>Asset ${x.asset_code || x.assetCode || x.id}</p></div><button class="remove" data-id="${x.id}">Remove</button></article>`).join('') : '<article class="cart-item"><div><h3>Your booking cart is empty</h3><p>Return to the catalog to add equipment.</p></div></article>'; document.querySelectorAll('.remove').forEach(button => button.onclick = () => { cart = cart.filter(x => Number(x.id) !== Number(button.dataset.id)); localStorage.setItem('mlmCart', JSON.stringify(cart)); draw(); }); };
  $('#clearCart').onclick = () => { cart = []; localStorage.setItem('mlmCart', '[]'); draw(); };
  $('#submit').onclick = async () => { const user = mlmApi.currentUser(); const dates = document.querySelectorAll('input[type="datetime-local"]'); const pickup = new Date(dates[0].value); const returned = new Date(dates[1].value); const hours = (returned - pickup) / 36e5; if (!user?.id) return toast('Sign in with a backend user before submitting a request.'); if (!cart.length) return toast('Add equipment from the catalog before submitting.'); if (Number.isNaN(pickup.getTime()) || Number.isNaN(returned.getTime()) || returned <= pickup) return toast('Choose a pickup time before the return time.'); if (hours > 72) return toast('The standard loan period is 72 hours maximum.'); try { const result = await mlmApi.createRequest({ requesterId: Number(user.id), equipmentIds: cart.map(x => Number(x.id)), purpose: document.querySelector('select').value, pickupStartsAt: pickup.toISOString(), pickupEndsAt: new Date(pickup.getTime() + 60 * 60 * 1000).toISOString(), returnStartsAt: returned.toISOString(), returnEndsAt: new Date(returned.getTime() + 60 * 60 * 1000).toISOString(), notes: document.querySelector('textarea')?.value || '' }); localStorage.setItem('mlmLastRequest', JSON.stringify(result)); localStorage.setItem('mlmCart', '[]'); location.href = 'history.html'; } catch (error) { toast(error.message); } };
  const cancel = document.querySelector('.form-actions .outline'); if (cancel) cancel.onclick = () => history.back();
  draw();
});
