(async function () {
  await window.mlmSessionReady; await mlmSession.requireAuth();
  const $ = selector => document.querySelector(selector); let cart = JSON.parse(localStorage.getItem('mlmCart') || '[]'); let maxLoanHours = 72;
  const toast = message => { $('#toast').textContent = message; $('#toast').classList.add('show'); setTimeout(() => $('#toast').classList.remove('show'), 3000); };
  const pad = value => String(value).padStart(2, '0'); const dateValue = (offset, time) => { const d = new Date(Date.now() + offset * 86400000); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}${time ? `T${time}` : ''}`; };
  $('#pickupDate').value = dateValue(1); $('#pickupTime').value = '14:00'; $('#returnDate').value = dateValue(2); $('#returnTime').value = '16:00';
  try { const policy = await mlmApi.policy(); maxLoanHours = Number(policy.standardLoanHours || maxLoanHours); } catch {} $('#loanPolicy').textContent = `ⓘ Standard loan period is ${maxLoanHours} hours maximum. The server will validate availability and dates.`;
  const draw = () => { $('#itemCount').textContent = `(${cart.length} Item${cart.length === 1 ? '' : 's'} Selected)`; $('#cartItems').innerHTML = cart.length ? cart.map(x => `<article class="cart-item"><div class="cart-thumb">◈</div><div><span class="tag">${x.category || 'Equipment'}</span><h3>${x.name}</h3><p>Asset ${x.asset_code || x.assetCode || x.id}</p></div><button class="remove" data-id="${x.id}">Remove</button></article>`).join('') : '<article class="cart-item"><div><h3>Your booking cart is empty</h3><p>Return to the catalog to add equipment.</p></div></article>'; document.querySelectorAll('.remove').forEach(button => button.onclick = () => { cart = cart.filter(x => Number(x.id) !== Number(button.dataset.id)); localStorage.setItem('mlmCart', JSON.stringify(cart)); draw(); }); };
  $('#clearCart').onclick = () => { cart = []; localStorage.setItem('mlmCart', '[]'); draw(); };
  $('#submit').onclick = async () => { if (!cart.length) return toast('Add equipment from the catalog before submitting.'); const pickup = new Date(`${$('#pickupDate').value}T${$('#pickupTime').value}`); const returned = new Date(`${$('#returnDate').value}T${$('#returnTime').value}`); const hours = (returned - pickup) / 36e5; if (Number.isNaN(pickup.getTime()) || Number.isNaN(returned.getTime()) || returned <= pickup) return toast('Choose a return date and time after pickup.'); if (hours > maxLoanHours) return toast(`The maximum loan period is ${maxLoanHours} hours.`); try { const result = await mlmApi.createRequest({ equipmentIds: cart.map(x => Number(x.id)), purpose: $('#purpose').value, pickupStartsAt: pickup.toISOString(), pickupEndsAt: new Date(pickup.getTime() + 3600000).toISOString(), returnStartsAt: returned.toISOString(), returnEndsAt: new Date(returned.getTime() + 3600000).toISOString(), notes: $('#notes').value }); localStorage.setItem('mlmLastRequest', JSON.stringify(result)); localStorage.setItem('mlmCart', '[]'); location.href = 'history.html'; } catch (error) { toast(error.message); } };
  draw();
})();
