const catalogApiReady = window.mlmApi ? Promise.resolve() : new Promise(resolve => { const s = document.createElement('script'); s.src = '../js/api.js'; s.onload = resolve; document.head.appendChild(s); });
catalogApiReady.then(() => window.mlmSessionReady).then(() => mlmSession.requireAuth()).then(async () => {
  let category = 'All';
  const $ = selector => document.querySelector(selector);
  const cart = () => JSON.parse(localStorage.getItem('mlmCart') || '[]');
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const classify = name => { const n = String(name || '').toLowerCase(); if (/camera|a6400|zv-e10|rx100/.test(n)) return 'Cameras'; if (/lens|mm f|art/.test(n)) return 'Lenses'; if (/mic|rode|røde|sennheiser|hollyland|zoom|headphone|mixer|recorder|audio/.test(n)) return 'Audio'; if (/light|godox|aputure|colbor|softbox|stand/.test(n)) return 'Lighting'; return 'Accessories'; };
  const brand = name => { const n = String(name || '').toLowerCase(); if (n.includes('sony')) return 'Sony'; if (n.includes('ttartisan')) return 'TTArtisans'; if (n.includes('sigma')) return 'Sigma'; if (n.includes('godox')) return 'Godox'; if (n.includes('rode') || n.includes('røde')) return 'RØDE'; if (n.includes('hollyland')) return 'Hollyland'; if (n.includes('zoom')) return 'Zoom'; return ''; };
  const listingImage = item => { const first = Array.isArray(item.images) ? item.images[0] : null; const url = typeof first === 'string' ? first : first?.url; if (!url) return null; try { const parsed = new URL(url, location.href); if (!['http:', 'https:'].includes(parsed.protocol)) return null; return { url: parsed.href, alt: (typeof first === 'object' && first.alt) || item.name, attribution: typeof first === 'object' ? first.attribution : '' }; } catch { return null; } };
  const renderBrands = units => { const target = $('#brandFilters'); if (!target) return; const current = new Set([...document.querySelectorAll('.brand-filter:checked')].map(input => input.value)); const brands = [...new Set(units.map(item => brand(item.name)).filter(Boolean))].sort(); target.innerHTML = brands.length ? brands.map(value => `<label><input class="brand-filter" value="${esc(value)}" type="checkbox" ${current.has(value) ? 'checked' : ''}> ${esc(value)}</label>`).join('') : '<p class="empty">No brands returned by the server.</p>'; document.querySelectorAll('.brand-filter').forEach(input => input.onchange = draw); };
  const normalizeListings = listings => listings.map(item => ({ ...item, total: Number(item.total_quantity ?? item.quantity ?? 0), available: Number(item.available_quantity ?? 0), id: item.id ?? item.available_equipment_ids?.[0] }));
  const draw = async () => {
    const filters = { q: $('#search').value, limit: 1000 };
    try {
      const result = await mlmApi.listings(filters);
      const listings = Array.isArray(result) ? result : (result.listings || result.items || []);
      renderBrands(listings);
      const selected = [...document.querySelectorAll('.brand-filter:checked')].map(x => x.value);
      const list = normalizeListings(listings).filter(item => (category === 'All' || (item.category || classify(item.name)) === category) && (!$('#available').checked || item.available > 0) && (!selected.length || selected.includes(brand(item.name))));
      const selectedIds = new Set(cart().map(x => Number(x.id)));
      $('#equipmentGrid').innerHTML = list.map(item => { const itemCategory = item.category || classify(item.name); const inCart = selectedIds.has(Number(item.id)); const availability = `${item.available} of ${item.total} available${item.lost_quantity ? ` · ${item.lost_quantity} lost` : ''}`; return `<article class="equipment-card"><div class="equipment-visual" aria-hidden="true">${itemCategory === 'Cameras' ? '◉' : itemCategory === 'Audio' ? '◌' : itemCategory === 'Lighting' ? '✦' : '◇'}</div><div class="equipment-body"><div class="equipment-meta"><span class="tag">${esc(itemCategory)}</span><span class="status ${item.available ? 'available' : 'maintenance'}">${esc(availability)}</span></div><h3>${esc(item.name)}</h3><p>${esc(item.description || item.location || '')}</p><div class="equipment-foot"><span class="asset">${esc(item.asset_code || `Listing ${item.listing_id || item.id}`)}</span><button class="${inCart || !item.available ? 'outline' : 'primary'}" ${inCart || !item.available ? 'disabled' : ''} data-add="${item.id}">${inCart ? '✓ Added to Cart' : item.available ? '+ Add to Booking' : 'Unavailable'}</button></div></div></article>`; }).join('') || '<p class="empty">No equipment matches these filters.</p>';
      document.querySelectorAll('.equipment-card').forEach((card, index) => { const image = listingImage(list[index]); if (!image) return; const visual = card.querySelector('.equipment-visual'); const imageElement = document.createElement('img'); imageElement.src = image.url; imageElement.alt = image.alt; imageElement.loading = 'lazy'; imageElement.style.cssText = 'width:100%;height:100%;object-fit:cover;display:block'; if (image.attribution) imageElement.title = image.attribution; visual.removeAttribute('aria-hidden'); visual.replaceChildren(imageElement); });
      const cartCount = $('#cartCount'); if (cartCount) cartCount.textContent = cart().length;
      document.querySelectorAll('[data-add]').forEach(button => button.onclick = () => { const item = list.find(x => Number(x.id) === Number(button.dataset.add)); const next = cart(); if (item && !next.some(x => Number(x.id) === Number(item.id))) { next.push(item); localStorage.setItem('mlmCart', JSON.stringify(next)); draw(); } });
    } catch (error) { $('#equipmentGrid').innerHTML = '<p class="empty">Equipment could not be loaded from the server.</p>'; mlmUiError(error.message); }
  };
  $('#search').oninput = draw; $('#available').onchange = draw; document.querySelectorAll('.brand-filter').forEach(x => x.onchange = draw); document.querySelectorAll('[data-category]').forEach(x => x.onclick = () => { category = x.dataset.category; document.querySelectorAll('[data-category]').forEach(y => y.classList.toggle('selected', y === x)); draw(); }); $('#clearFilters').onclick = () => { $('#search').value = ''; $('#available').checked = false; document.querySelectorAll('.brand-filter').forEach(x => x.checked = false); category = 'All'; document.querySelectorAll('[data-category]').forEach((x, i) => x.classList.toggle('selected', i === 0)); draw(); }; draw();
});
