const catalogApiReady = window.mlmApi ? Promise.resolve() : new Promise(resolve => { const s = document.createElement('script'); s.src = '../js/api.js'; s.onload = resolve; document.head.appendChild(s); });
catalogApiReady.then(() => window.mlmSessionReady).then(() => mlmSession.requireAuth()).then(async () => {
  let category = 'All';
  const $ = selector => document.querySelector(selector);
  const cart = () => JSON.parse(localStorage.getItem('mlmCart') || '[]');
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const classify = name => { const n = String(name || '').toLowerCase(); if (/camera|a6400|zv-e10|rx100/.test(n)) return 'Cameras'; if (/lens|mm f|art/.test(n)) return 'Lenses'; if (/mic|rode|røde|sennheiser|hollyland|zoom|headphone|mixer|recorder|audio/.test(n)) return 'Audio'; if (/light|godox|aputure|colbor|softbox|stand/.test(n)) return 'Lighting'; return 'Accessories'; };
  const brand = name => { const n = String(name || '').toLowerCase(); if (n.includes('sony')) return 'Sony'; if (n.includes('ttartisan')) return 'TTArtisans'; if (n.includes('sigma')) return 'Sigma'; if (n.includes('godox')) return 'Godox'; if (n.includes('rode') || n.includes('røde')) return 'RØDE'; if (n.includes('hollyland')) return 'Hollyland'; if (n.includes('zoom')) return 'Zoom'; return ''; };
  const aggregate = units => [...units.reduce((groups, unit) => { const key = unit.listing_id || unit.name; const group = groups.get(key) || { ...unit, units: [] }; group.units.push(unit); groups.set(key, group); return groups; }, new Map()).values()].map(group => { const available = group.units.filter(unit => unit.status === 'available'); return { ...group, id: (available[0] || group.units[0])?.id, total: group.units.length, available: available.length, units: undefined }; });
  const draw = async () => {
    const filters = { q: $('#search').value, limit: 1000 };
    try {
      const result = await mlmApi.equipment(filters);
      const units = Array.isArray(result) ? result : (result.equipment || result.items || []);
      const selected = [...document.querySelectorAll('.brand-filter:checked')].map(x => x.value);
      const list = aggregate(units).filter(item => (category === 'All' || classify(item.name) === category) && (!$('#available').checked || item.available > 0) && (!selected.length || selected.includes(brand(item.name))));
      const selectedIds = new Set(cart().map(x => Number(x.id)));
      $('#equipmentGrid').innerHTML = list.map(item => { const itemCategory = classify(item.name); const inCart = selectedIds.has(Number(item.id)); const availability = `${item.available} of ${item.total} available`; return `<article class="equipment-card"><div class="equipment-visual" aria-hidden="true">${itemCategory === 'Cameras' ? '◉' : itemCategory === 'Audio' ? '◌' : itemCategory === 'Lighting' ? '✦' : '◇'}</div><div class="equipment-body"><div class="equipment-meta"><span class="tag">${esc(itemCategory)}</span><span class="status ${item.available ? 'available' : 'maintenance'}">${esc(availability)}</span></div><h3>${esc(item.name)}</h3><p>${esc(item.description || item.location || 'Backend equipment listing')}</p><div class="equipment-foot"><span class="asset">${esc(item.asset_code || `Listing ${item.listing_id || item.id}`)}</span><button class="${inCart || !item.available ? 'outline' : 'primary'}" ${inCart || !item.available ? 'disabled' : ''} data-add="${item.id}">${inCart ? '✓ Added to Cart' : item.available ? '+ Add to Booking' : 'Unavailable'}</button></div></div></article>`; }).join('') || '<p class="empty">No equipment matches these filters.</p>';
      $('#cartCount').textContent = cart().length;
      document.querySelectorAll('[data-add]').forEach(button => button.onclick = () => { const item = list.find(x => Number(x.id) === Number(button.dataset.add)); const next = cart(); if (item && !next.some(x => Number(x.id) === Number(item.id))) { next.push(item); localStorage.setItem('mlmCart', JSON.stringify(next)); draw(); } });
    } catch (error) { $('#equipmentGrid').innerHTML = '<p class="empty">Equipment could not be loaded from the server.</p>'; mlmUiError(error.message); }
  };
  $('#search').oninput = draw; $('#available').onchange = draw; document.querySelectorAll('.brand-filter').forEach(x => x.onchange = draw); document.querySelectorAll('[data-category]').forEach(x => x.onclick = () => { category = x.dataset.category; document.querySelectorAll('[data-category]').forEach(y => y.classList.toggle('selected', y === x)); draw(); }); $('#clearFilters').onclick = () => { $('#search').value = ''; $('#available').checked = false; document.querySelectorAll('.brand-filter').forEach(x => x.checked = false); category = 'All'; document.querySelectorAll('[data-category]').forEach((x, i) => x.classList.toggle('selected', i === 0)); draw(); }; draw();
});
