const historyApiReady = window.mlmApi ? Promise.resolve() : new Promise(resolve => { const s = document.createElement('script'); s.src = '../js/api.js'; s.onload = resolve; document.head.appendChild(s); });
historyApiReady.then(() => window.mlmSessionReady).then(() => mlmSession.requireAuth()).then(async () => {
  const tbody = document.querySelector('#historyRows'); const user = mlmApi.currentUser(); let rows = [];
  const format = value => value ? new Date(value).toLocaleString() : '—';
  const modal = document.querySelector('#extensionModal'); const form = document.querySelector('#extensionForm');
  const openExtension = request => { document.querySelector('#extensionId').value = request.id; document.querySelector('#extensionBooking').textContent = `Booking #${request.id} · ${(request.items || []).map(item => item.name || item.equipment_id).join(', ')}`; const currentReturn = request.windows?.find(window => window.kind === 'return')?.ends_at; const date = currentReturn ? new Date(currentReturn) : new Date(Date.now() + 86400000); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); document.querySelector('#extensionDate').value = date.toISOString().slice(0, 16); document.querySelector('#extensionReason').value = ''; modal.style.display = 'grid'; document.querySelector('#extensionDate').focus(); };
  const closeExtension = () => { modal.style.display = 'none'; form.reset(); };
  document.querySelector('#cancelExtension')?.addEventListener('click', closeExtension); modal?.addEventListener('click', event => { if (event.target === modal) closeExtension(); });
  let activeFilter = 'current';
  const setActiveTab = filter => document.querySelectorAll('.history-tabs button').forEach(button => { const active = button.dataset.historyFilter === filter; button.classList.toggle('selected', active); button.setAttribute('aria-selected', String(active)); });
  const render = filter => { activeFilter = filter; setActiveTab(filter); const visible = rows.filter(request => filter === 'all' || (filter === 'current' && ['approved', 'pickup_pending', 'picked_up', 'overdue'].includes(request.status)) || (filter === 'pending' && request.status === 'pending') || (filter === 'past' && ['returned', 'rejected', 'cancelled'].includes(request.status))); tbody.innerHTML = visible.map(request => { const canReturn = ['approved', 'pickup_pending', 'picked_up', 'overdue'].includes(request.status) && !request.return_submission; const action = canReturn ? `<a href="return.html?request=${request.id}&from=history">Return &amp; Damage</a>` : request.return_submission ? '<span class="status completed">Return submitted</span>' : ''; return `<tr><td><b>${request.id}</b></td><td>${(request.items || []).map(item => item.name || item.equipment_id).join(', ')}</td><td>${format(request.windows?.find(x => x.kind === 'pickup')?.starts_at)}</td><td>${format(request.windows?.find(x => x.kind === 'return')?.ends_at)}</td><td><span class="status ${request.status}">${request.status}</span></td><td>${action} ${['approved','pickup_pending','picked_up'].includes(request.status) ? `<button class="extend" data-id="${request.id}">Request extension</button>` : ''}</td></tr>`; }).join('') || '<tr><td colspan="6">No requests found.</td></tr>'; document.querySelectorAll('.extend').forEach(button => button.onclick = () => openExtension(rows.find(request => Number(request.id) === Number(button.dataset.id)))); };
  form?.addEventListener('submit', async event => { event.preventDefault(); try { await mlmApi.extension({ requestId: Number(document.querySelector('#extensionId').value), startsAt: new Date().toISOString(), endsAt: new Date(document.querySelector('#extensionDate').value).toISOString(), notes: document.querySelector('#extensionReason').value }); closeExtension(); mlmUiError('Extension request submitted.'); const result = await mlmApi.requests(`?requesterId=${encodeURIComponent(user.id)}`); rows = Array.isArray(result) ? result : (result.requests || []); render(activeFilter); } catch (error) { mlmUiError(error.message); } });
  try { if (!user?.id) throw new Error('Sign in before viewing booking history.'); const result = await mlmApi.requests(`?requesterId=${encodeURIComponent(user.id)}`); rows = Array.isArray(result) ? result : (result.requests || []); document.querySelectorAll('.history-tabs button').forEach((button, index) => { button.dataset.historyFilter = ['current', 'past', 'pending'][index] || 'all'; button.setAttribute('aria-selected', String(index === 0)); button.onclick = () => render(button.dataset.historyFilter); }); render('current'); } catch (error) { tbody.innerHTML = `<tr><td colspan="6">${error.message}</td></tr>`; }
});
