(async function () {
  if (!window.mlmApi) await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = '../js/api.js'; script.onload = resolve; script.onerror = reject; document.head.appendChild(script); });
  await window.mlmSessionReady;
  await mlmSession.requireAuth();
  const target = document.querySelector('#notifications'); let notes = [];
  const render = filter => { const filtered = filter === 'all' ? notes : notes.filter(note => note.category === filter); target.innerHTML = filtered.map(note => `<article class="notice-card"><i class="notice-icon">${note.icon}</i><div><h2>${note.title}</h2><p>${note.message}</p>${note.action}<small>${note.time ? new Date(note.time).toLocaleString() : ''}</small></div></article>`).join('') || '<p>No notifications for this filter.</p>'; };
  try { const data = await mlmApi.requests(); const requests = Array.isArray(data) ? data : (data.requests || []); notes = requests.flatMap(request => { const itemNames = (request.items || []).map(item => item.name || item.equipment_id).join(', ') || 'equipment'; const pickup = request.windows?.find(window => window.kind === 'pickup'); const category = request.status === 'approved' ? 'requests' : request.status === 'rejected' ? 'system' : 'reminders'; return [{ category, icon: request.status === 'approved' ? '✓' : '•', title: `Request #${request.id} — ${request.status}`, message: `Request #${request.id} for ${itemNames} is ${request.status}.`, action: request.status === 'approved' && pickup ? `<a class="primary" href="pickup-pass.html?booking=${request.id}">View Pickup Pass</a>` : '', time: request.updated_at || request.created_at }]; }); render('all'); } catch (error) { target.innerHTML = `<p>${error.message}</p>`; }
  document.querySelectorAll('.notification-menu button').forEach((button, index) => { button.dataset.notificationFilter = ['all', 'requests', 'reminders', 'system'][index] || 'all'; button.onclick = () => render(button.dataset.notificationFilter); });
  document.querySelector('#readAll').onclick = event => { event.target.textContent = 'All caught up ✓'; };
})();
