(async function () {
  if (!window.mlmApi) await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = '../js/api.js'; script.onload = resolve; script.onerror = reject; document.head.appendChild(script); });
  await window.mlmSessionReady;
  await mlmSession.requireAuth();
  const target = document.querySelector('#notifications'); let notes = [];
  const render = filter => { const filtered = filter === 'all' ? notes : notes.filter(note => note.category === filter); target.innerHTML = filtered.map(note => `<article class="notice-card"><i class="notice-icon">${note.icon}</i><div><h2>${note.title}</h2><p>${note.message}</p>${note.action}<small>${note.time ? new Date(note.time).toLocaleString() : ''}</small></div></article>`).join('') || '<p>No notifications for this filter.</p>'; document.querySelectorAll('[data-count]').forEach(counter => { const category = counter.dataset.count; counter.textContent = category === 'all' ? notes.length : notes.filter(note => note.category === category).length; }); };
  try { const data = await mlmApi.requests(); const requests = Array.isArray(data) ? data : (data.requests || []); notes = requests.flatMap(request => { const itemNames = (request.items || []).map(item => item.name || item.equipment_id).join(', ') || 'equipment'; const pickup = [...(request.windows || [])].reverse().find(window => window.kind === 'pickup' && ['approved', 'accepted', 'rejected'].includes(window.status)); const category = request.status === 'rejected' ? 'system' : 'reminders'; const action = request.status === 'pickup_pending' && pickup?.status === 'approved' ? `<a class="primary" href="profile.html">Review pickup time</a>` : ''; return [{ category, icon: request.status === 'pickup_pending' ? '!' : '•', title: `Request #${request.id} — ${request.status}`, message: `Request #${request.id} for ${itemNames} is ${request.status}.`, action, time: request.updated_at || request.created_at }]; }); render('all'); } catch (error) { target.innerHTML = `<p>${error.message}</p>`; }
  document.querySelectorAll('.notification-menu button').forEach(button => { button.dataset.notificationFilter = button.dataset.notificationCategory || 'all'; button.onclick = () => render(button.dataset.notificationFilter); });
  document.querySelector('#readAll').onclick = event => { event.target.textContent = 'All caught up ✓'; };
})();
